name: wehd_env

channels:
  - conda-forge

dependencies:
  - python=3.8
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - scikit-learn-extra=0.2.0
  - numpy=1.21.1
  - pip
  - pip:
    - gradient-free-optimizers==0.3.2
